%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/42dd0cea20498fd544b152c4e2c0a419bb7e266a/exercises/crypto-square/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(crypto_square_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_empty_plaintext_results_in_an_empty_ciphertext_test_'() ->
    {"empty plaintext results in an empty "
     "ciphertext",
     ?_assertEqual([], crypto_square:ciphertext([]))}.

'2_lowercase_test_'() ->
    {"Lowercase",
     ?_assertEqual("a", crypto_square:ciphertext("A"))}.

'3_remove_spaces_test_'() ->
    {"Remove spaces",
     ?_assertEqual("b", crypto_square:ciphertext("  b "))}.

'4_remove_punctuation_test_'() ->
    {"Remove punctuation",
     ?_assertEqual("1", crypto_square:ciphertext("@1,%!"))}.

'5_9_character_plaintext_results_in_3_chunks_of_3_characters_test_'() ->
    {"9 character plaintext results in 3 chunks "
     "of 3 characters",
     ?_assertEqual("tsf hiu isn",
		   crypto_square:ciphertext("This is fun!"))}.

'6_8_character_plaintext_results_in_3_chunks_the_last_one_with_a_trailing_space_test_'() ->
    {"8 character plaintext results in 3 chunks, "
     "the last one with a trailing space",
     ?_assertEqual("clu hlt io ",
		   crypto_square:ciphertext("Chill out."))}.

'7_54_character_plaintext_results_in_7_chunks_the_last_two_with_trailing_spaces_test_'() ->
    {"54 character plaintext results in 7 "
     "chunks, the last two with trailing spaces",
     ?_assertEqual("imtgdvs fearwer mayoogo anouuio ntnnlvt "
		   "wttddes aohghn  sseoau ",
		   crypto_square:ciphertext("If man was meant to stay on the ground, "
					    "god would have given us roots."))}.
