%% Based on canonical data version 1.4.1
%% https://github.com/exercism/problem-specifications/raw/master/exercises/pangram/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(pangram_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_sentence_empty_test'() ->
    ?assertNot(pangram:is_pangram([])).

'2_recognizes_a_perfect_lower_case_pangram_test'() ->
    ?assert(pangram:is_pangram("abcdefghijklmnopqrstuvwxyz")).

'3_pangram_with_only_lower_case_test'() ->
    ?assert(pangram:is_pangram("the quick brown fox jumps over the lazy "
			       "dog")).

'4_missing_character_x_test'() ->
    ?assertNot(pangram:is_pangram("a quick movement of the enemy will jeopardize "
				  "five gunboats")).

'5_another_missing_character_eg_h_test'() ->
    ?assertNot(pangram:is_pangram("five boxing wizards jump quickly at it")).

'6_pangram_with_underscores_test'() ->
    ?assert(pangram:is_pangram("the_quick_brown_fox_jumps_over_the_lazy_dog")).

'7_pangram_with_numbers_test'() ->
    ?assert(pangram:is_pangram("the 1 quick brown fox jumps over the "
			       "2 lazy dogs")).

'8_missing_letters_replaced_by_numbers_test'() ->
    ?assertNot(pangram:is_pangram("7h3 qu1ck brown fox jumps ov3r 7h3 lazy "
				  "dog")).

'9_pangram_with_mixed_case_and_punctuation_test'() ->
    ?assert(pangram:is_pangram("\"Five quacking Zephyrs jolt my wax "
			       "bed.\"")).

'10_upper_and_lower_case_versions_of_the_same_character_should_not_be_counted_separately_test'() ->
    ?assertNot(pangram:is_pangram("the quick brown fox jumps over with "
				  "lazy FX")).
