%% Based on canonical data version 1.0.0-1
%% https://github.com/exercism/problem-specifications/raw/master/exercises/armstrong-numbers/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(armstrong_numbers_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_single_digit_numbers_are_armstrong_numbers_test_'() ->
    {"Single digit numbers are Armstrong numbers",
     ?_assert(armstrong_numbers:is_armstrong_number(5))}.

'2_there_are_no_2_digit_armstrong_numbers_test_'() ->
    {"There are no 2 digit Armstrong numbers",
     ?_assertNot(armstrong_numbers:is_armstrong_number(10))}.

'3_three_digit_number_that_is_an_armstrong_number_test_'() ->
    {"Three digit number that is an Armstrong "
     "number",
     ?_assert(armstrong_numbers:is_armstrong_number(153))}.

'4_three_digit_number_that_is_not_an_armstrong_number_test_'() ->
    {"Three digit number that is not an Armstrong "
     "number",
     ?_assertNot(armstrong_numbers:is_armstrong_number(100))}.

'5_four_digit_number_that_is_an_armstrong_number_test_'() ->
    {"Four digit number that is an Armstrong "
     "number",
     ?_assert(armstrong_numbers:is_armstrong_number(9474))}.

'6_four_digit_number_that_is_not_an_armstrong_number_test_'() ->
    {"Four digit number that is not an Armstrong "
     "number",
     ?_assertNot(armstrong_numbers:is_armstrong_number(9475))}.

'7_seven_digit_number_that_is_an_armstrong_number_test_'() ->
    {"Seven digit number that is an Armstrong "
     "number",
     ?_assert(armstrong_numbers:is_armstrong_number(9926315))}.

'8_seven_digit_number_that_is_not_an_armstrong_number_test_'() ->
    {"Seven digit number that is not an Armstrong "
     "number",
     ?_assertNot(armstrong_numbers:is_armstrong_number(9926314))}.
