%% Based on canonical data version 1.7.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/isogram/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(isogram_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_empty_string_test'() ->
    ?assert(isogram:is_isogram([])).

'2_isogram_with_only_lower_case_characters_test'() ->
    ?assert(isogram:is_isogram("isogram")).

'3_word_with_one_duplicated_character_test'() ->
    ?assertNot(isogram:is_isogram("eleven")).

'4_word_with_one_duplicated_character_from_the_end_of_the_alphabet_test'() ->
    ?assertNot(isogram:is_isogram("zzyzx")).

'5_longest_reported_english_isogram_test'() ->
    ?assert(isogram:is_isogram("subdermatoglyphic")).

'6_word_with_duplicated_character_in_mixed_case_test'() ->
    ?assertNot(isogram:is_isogram("Alphabet")).

'7_word_with_duplicated_character_in_mixed_case_lowercase_first_test'() ->
    ?assertNot(isogram:is_isogram("alphAbet")).

'8_hypothetical_isogrammic_word_with_hyphen_test'() ->
    ?assert(isogram:is_isogram("thumbscrew-japingly")).

'9_hypothetical_word_with_duplicated_character_following_hyphen_test'() ->
    ?assertNot(isogram:is_isogram("thumbscrew-jappingly")).

'10_isogram_with_duplicated_hyphen_test'() ->
    ?assert(isogram:is_isogram("six-year-old")).

'11_made_up_name_that_is_an_isogram_test'() ->
    ?assert(isogram:is_isogram("Emily Jung Schwartzkopf")).

'12_duplicated_character_in_the_middle_test'() ->
    ?assertNot(isogram:is_isogram("accentor")).

'13_same_first_and_last_characters_test'() ->
    ?assertNot(isogram:is_isogram("angola")).
