%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/42dd0cea20498fd544b152c4e2c0a419bb7e266a/exercises/isogram/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(isogram_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_empty_string_test_'() ->
    {"empty string", ?_assert(isogram:is_isogram([]))}.

'2_isogram_with_only_lower_case_characters_test_'() ->
    {"isogram with only lower case characters",
     ?_assert(isogram:is_isogram("isogram"))}.

'3_word_with_one_duplicated_character_test_'() ->
    {"word with one duplicated character",
     ?_assertNot(isogram:is_isogram("eleven"))}.

'4_word_with_one_duplicated_character_from_the_end_of_the_alphabet_test_'() ->
    {"word with one duplicated character from "
     "the end of the alphabet",
     ?_assertNot(isogram:is_isogram("zzyzx"))}.

'5_longest_reported_english_isogram_test_'() ->
    {"longest reported english isogram",
     ?_assert(isogram:is_isogram("subdermatoglyphic"))}.

'6_word_with_duplicated_character_in_mixed_case_test_'() ->
    {"word with duplicated character in mixed "
     "case",
     ?_assertNot(isogram:is_isogram("Alphabet"))}.

'7_word_with_duplicated_character_in_mixed_case_lowercase_first_test_'() ->
    {"word with duplicated character in mixed "
     "case, lowercase first",
     ?_assertNot(isogram:is_isogram("alphAbet"))}.

'8_hypothetical_isogrammic_word_with_hyphen_test_'() ->
    {"hypothetical isogrammic word with hyphen",
     ?_assert(isogram:is_isogram("thumbscrew-japingly"))}.

'9_hypothetical_word_with_duplicated_character_following_hyphen_test_'() ->
    {"hypothetical word with duplicated character "
     "following hyphen",
     ?_assertNot(isogram:is_isogram("thumbscrew-jappingly"))}.

'10_isogram_with_duplicated_hyphen_test_'() ->
    {"isogram with duplicated hyphen",
     ?_assert(isogram:is_isogram("six-year-old"))}.

'11_made_up_name_that_is_an_isogram_test_'() ->
    {"made-up name that is an isogram",
     ?_assert(isogram:is_isogram("Emily Jung Schwartzkopf"))}.

'12_duplicated_character_in_the_middle_test_'() ->
    {"duplicated character in the middle",
     ?_assertNot(isogram:is_isogram("accentor"))}.

'13_same_first_and_last_characters_test_'() ->
    {"same first and last characters",
     ?_assertNot(isogram:is_isogram("angola"))}.
