%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/42dd0cea20498fd544b152c4e2c0a419bb7e266a/exercises/darts/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(darts_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_missed_target_test_'() ->
    {"Missed target", ?_assertEqual(0, darts:score(-9, 9))}.

'2_on_the_outer_circle_test_'() ->
    {"On the outer circle",
     ?_assertEqual(1, darts:score(0, 10))}.

'3_on_the_middle_circle_test_'() ->
    {"On the middle circle",
     ?_assertEqual(5, darts:score(-5, 0))}.

'4_on_the_inner_circle_test_'() ->
    {"On the inner circle",
     ?_assertEqual(10, darts:score(0, -1))}.

'5_exactly_on_centre_test_'() ->
    {"Exactly on centre",
     ?_assertEqual(10, darts:score(0, 0))}.

'6_near_the_centre_test_'() ->
    {"Near the centre",
     ?_assertEqual(10, darts:score(-1.0e-1, -1.0e-1))}.

'7_just_within_the_inner_circle_test_'() ->
    {"Just within the inner circle",
     ?_assertEqual(10,
		   darts:score(6.99999999999999955591e-1,
			       6.99999999999999955591e-1))}.

'8_just_outside_the_inner_circle_test_'() ->
    {"Just outside the inner circle",
     ?_assertEqual(5, darts:score(8.0e-1, -8.0e-1))}.

'9_just_within_the_middle_circle_test_'() ->
    {"Just within the middle circle",
     ?_assertEqual(5, darts:score(-3.5, 3.5))}.

'10_just_outside_the_middle_circle_test_'() ->
    {"Just outside the middle circle",
     ?_assertEqual(1, darts:score(-3.6, -3.6))}.

'11_just_within_the_outer_circle_test_'() ->
    {"Just within the outer circle",
     ?_assertEqual(1, darts:score(-7.0, 7.0))}.

'12_just_outside_the_outer_circle_test_'() ->
    {"Just outside the outer circle",
     ?_assertEqual(0,
		   darts:score(7.09999999999999964473,
			       -7.09999999999999964473))}.

'13_asymmetric_position_between_the_inner_and_middle_circles_test_'() ->
    {"Asymmetric position between the inner "
     "and middle circles",
     ?_assertEqual(5, darts:score(5.0e-1, -4))}.
