%% Based on canonical data version 1.0.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/darts/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(darts_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_a_dart_lands_outside_the_target_test'() ->
    ?assertEqual(0,
		 darts:score(1.53e+1, 1.31999999999999992895e+1)).

'2_a_dart_lands_just_in_the_border_of_the_target_test'() ->
    ?assertEqual(1, darts:score(10, 0)).

'3_a_dart_lands_in_the_middle_circle_test'() ->
    ?assertEqual(5, darts:score(3, 3.7)).

'4_a_dart_lands_right_in_the_border_between_outside_and_middle_circles_test'() ->
    ?assertEqual(5, darts:score(0, 5)).

'5_a_dart_lands_in_the_inner_circle_test'() ->
    ?assertEqual(10, darts:score(0, 0)).
