%% Based on canonical data version 1.3.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/luhn/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(luhn_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_single_digit_strings_can_not_be_valid_test'() ->
    ?assertNot(luhn:valid("1")).

'2_a_single_zero_is_invalid_test'() ->
    ?assertNot(luhn:valid("0")).

'3_a_simple_valid_sin_that_remains_valid_if_reversed_test'() ->
    ?assert(luhn:valid("059")).

'4_a_simple_valid_sin_that_becomes_invalid_if_reversed_test'() ->
    ?assert(luhn:valid("59")).

'5_a_valid_canadian_sin_test'() ->
    ?assert(luhn:valid("055 444 285")).

'6_invalid_canadian_sin_test'() ->
    ?assertNot(luhn:valid("055 444 286")).

'7_invalid_credit_card_test'() ->
    ?assertNot(luhn:valid("8273 1232 7352 0569")).

'8_valid_number_with_an_even_number_of_digits_test'() ->
    ?assert(luhn:valid("095 245 88")).

'9_valid_strings_with_a_non_digit_included_become_invalid_test'() ->
    ?assertNot(luhn:valid("055a 444 285")).

'10_valid_strings_with_punctuation_included_become_invalid_test'() ->
    ?assertNot(luhn:valid("055-444-285")).

'11_valid_strings_with_symbols_included_become_invalid_test'() ->
    ?assertNot(luhn:valid("055£ 444$ 285")).

'12_single_zero_with_space_is_invalid_test'() ->
    ?assertNot(luhn:valid(" 0")).

'13_more_than_a_single_zero_is_valid_test'() ->
    ?assert(luhn:valid("0000 0")).

'14_input_digit_9_is_correctly_converted_to_output_digit_9_test'() ->
    ?assert(luhn:valid("091")).

'15_strings_with_non_digits_is_invalid_test'() ->
    ?assertNot(luhn:valid(":9")).
