%% Based on canonical data version 1.2.0-1
%% https://github.com/exercism/problem-specifications/raw/master/exercises/allergies/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(allergies_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_no_allergies_means_not_allergic_test_'() ->
    Score = 0,
    [{"peanuts",
      ?_assertNot(allergies:is_allergic_to(peanuts, Score))},
     {"cats",
      ?_assertNot(allergies:is_allergic_to(cats, Score))},
     {"strawberries",
      ?_assertNot(allergies:is_allergic_to(strawberries,
					   Score))}].

'2_is_allergic_to_eggs_test_'() ->
    Score = 1,
    [{"eggs",
      ?_assert(allergies:is_allergic_to(eggs, Score))}].

'3_allergic_to_eggs_in_addition_to_other_stuff_test_'() ->
    Score = 5,
    [{"eggs",
      ?_assert(allergies:is_allergic_to(eggs, Score))},
     {"shellfish",
      ?_assert(allergies:is_allergic_to(shellfish, Score))},
     {"strawberries",
      ?_assertNot(allergies:is_allergic_to(strawberries,
					   Score))}].

'4_allergic_to_strawberries_but_not_peanuts_test_'() ->
    Score = 9,
    [{"eggs",
      ?_assert(allergies:is_allergic_to(eggs, Score))},
     {"peanuts",
      ?_assertNot(allergies:is_allergic_to(peanuts, Score))},
     {"shellfish",
      ?_assertNot(allergies:is_allergic_to(shellfish,
					   Score))},
     {"strawberries",
      ?_assert(allergies:is_allergic_to(strawberries,
					Score))}].

'5_no_allergies_at_all_test_'() ->
    {"no allergies at all",
     ?_assertMatch([], lists:sort(allergies:allergies(0)))}.

'6_allergic_to_just_eggs_test_'() ->
    {"allergic to just eggs",
     ?_assertMatch([eggs],
		   lists:sort(allergies:allergies(1)))}.

'7_allergic_to_just_peanuts_test_'() ->
    {"allergic to just peanuts",
     ?_assertMatch([peanuts],
		   lists:sort(allergies:allergies(2)))}.

'8_allergic_to_just_strawberries_test_'() ->
    {"allergic to just strawberries",
     ?_assertMatch([strawberries],
		   lists:sort(allergies:allergies(8)))}.

'9_allergic_to_eggs_and_peanuts_test_'() ->
    {"allergic to eggs and peanuts",
     ?_assertMatch([eggs, peanuts],
		   lists:sort(allergies:allergies(3)))}.

'10_allergic_to_more_than_eggs_but_not_peanuts_test_'() ->
    {"allergic to more than eggs but not peanuts",
     ?_assertMatch([eggs, shellfish],
		   lists:sort(allergies:allergies(5)))}.

'11_allergic_to_lots_of_stuff_test_'() ->
    {"allergic to lots of stuff",
     ?_assertMatch([cats, chocolate, pollen, strawberries,
		    tomatoes],
		   lists:sort(allergies:allergies(248)))}.

'12_allergic_to_everything_test_'() ->
    {"allergic to everything",
     ?_assertMatch([cats, chocolate, eggs, peanuts, pollen,
		    shellfish, strawberries, tomatoes],
		   lists:sort(allergies:allergies(255)))}.

'13_ignore_non_allergen_score_parts_test_'() ->
    {"ignore non allergen score parts",
     ?_assertMatch([cats, chocolate, eggs, pollen, shellfish,
		    strawberries, tomatoes],
		   lists:sort(allergies:allergies(509)))}.
