%% Based on canonical data version 1.1.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/allergies/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(allergies_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_no_allergies_means_not_allergic_test'() ->
    ?assertNot(allergies:is_allergic_to(peanuts, 0)),
    ?assertNot(allergies:is_allergic_to(cats, 0)),
    ?assertNot(allergies:is_allergic_to(strawberries, 0)).

'2_is_allergic_to_eggs_test'() ->
    ?assert(allergies:is_allergic_to(eggs, 1)).

'3_allergic_to_eggs_in_addition_to_other_stuff_test'() ->
    ?assert(allergies:is_allergic_to(eggs, 5)),
    ?assert(allergies:is_allergic_to(shellfish, 5)),
    ?assertNot(allergies:is_allergic_to(strawberries, 5)).

'4_no_allergies_at_all_test'() ->
    ?assertMatch([], lists:sort(allergies:allergies(0))).

'5_allergic_to_just_eggs_test'() ->
    ?assertMatch([eggs],
		 lists:sort(allergies:allergies(1))).

'6_allergic_to_just_peanuts_test'() ->
    ?assertMatch([peanuts],
		 lists:sort(allergies:allergies(2))).

'7_allergic_to_just_strawberries_test'() ->
    ?assertMatch([strawberries],
		 lists:sort(allergies:allergies(8))).

'8_allergic_to_eggs_and_peanuts_test'() ->
    ?assertMatch([eggs, peanuts],
		 lists:sort(allergies:allergies(3))).

'9_allergic_to_more_than_eggs_but_not_peanuts_test'() ->
    ?assertMatch([eggs, shellfish],
		 lists:sort(allergies:allergies(5))).

'10_allergic_to_lots_of_stuff_test'() ->
    ?assertMatch([cats, chocolate, pollen, strawberries,
		  tomatoes],
		 lists:sort(allergies:allergies(248))).

'11_allergic_to_everything_test'() ->
    ?assertMatch([cats, chocolate, eggs, peanuts, pollen,
		  shellfish, strawberries, tomatoes],
		 lists:sort(allergies:allergies(255))).

'12_ignore_non_allergen_score_parts_test'() ->
    ?assertMatch([cats, chocolate, eggs, pollen, shellfish,
		  strawberries, tomatoes],
		 lists:sort(allergies:allergies(509))).
