%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/42dd0cea20498fd544b152c4e2c0a419bb7e266a/exercises/etl/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(etl_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_single_letter_test_'() ->
    Input=[
        {1, ["A"]}
    ],
    Expected=[
        {"a", 1}
    ],
    {"single letter",
     ?_assertEqual(lists:sort(Expected),
		   lists:sort(etl:transform(Input)))}.

'2_single_score_with_multiple_letters_test_'() ->
    Input=[
        {1, ["A", "E", "I", "O", "U"]}
    ],
    Expected=[
        {"a", 1},
        {"e", 1},
        {"i", 1},
        {"o", 1},
        {"u", 1}
    ],
    {"single score with multiple letters",
     ?_assertEqual(lists:sort(Expected),
		   lists:sort(etl:transform(Input)))}.

'3_multiple_scores_with_multiple_letters_test_'() ->
    Input=[
        {1, ["A", "E"]},
        {2, ["D", "G"]}
    ],
    Expected=[
        {"a", 1},
        {"d", 2},
        {"e", 1},
        {"g", 2}
    ],
    {"multiple scores with multiple letters",
     ?_assertEqual(lists:sort(Expected),
		   lists:sort(etl:transform(Input)))}.

'4_multiple_scores_with_differing_numbers_of_letters_test_'() ->
    Input=[
        {1, ["A", "E", "I", "O", "U", "L", "N", "R", "S", "T"]},
        {2, ["D", "G"]},
        {3, ["B", "C", "M", "P"]},
        {4, ["F", "H", "V", "W", "Y"]},
        {5, ["K"]},
        {8, ["J", "X"]},
        {10, ["Q", "Z"]}
    ],
    Expected=[
        {"a", 1},
        {"b", 3},
        {"c", 3},
        {"d", 2},
        {"e", 1},
        {"f", 4},
        {"g", 2},
        {"h", 4},
        {"i", 1},
        {"j", 8},
        {"k", 5},
        {"l", 1},
        {"m", 3},
        {"n", 1},
        {"o", 1},
        {"p", 3},
        {"q", 10},
        {"r", 1},
        {"s", 1},
        {"t", 1},
        {"u", 1},
        {"v", 4},
        {"w", 4},
        {"x", 8},
        {"y", 4},
        {"z", 10}
    ],
    {"multiple scores with differing numbers "
     "of letters",
     ?_assertEqual(lists:sort(Expected),
		   lists:sort(etl:transform(Input)))}.
