%% Based on canonical data version 1.1.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/scrabble-score/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(scrabble_score_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_lowercase_letter_test'() ->
    ?assertEqual(1, scrabble_score:score("a")).

'2_uppercase_letter_test'() ->
    ?assertEqual(1, scrabble_score:score("A")).

'3_valuable_letter_test'() ->
    ?assertEqual(4, scrabble_score:score("f")).

'4_short_word_test'() ->
    ?assertEqual(2, scrabble_score:score("at")).

'5_short_valuable_word_test'() ->
    ?assertEqual(12, scrabble_score:score("zoo")).

'6_medium_word_test'() ->
    ?assertEqual(6, scrabble_score:score("street")).

'7_medium_valuable_word_test'() ->
    ?assertEqual(22, scrabble_score:score("quirky")).

'8_long_mixed_case_word_test'() ->
    ?assertEqual(41,
		 scrabble_score:score("OxyphenButazone")).

'9_english_like_word_test'() ->
    ?assertEqual(8, scrabble_score:score("pinata")).

'10_empty_input_test'() ->
    ?assertEqual(0, scrabble_score:score([])).

'11_entire_alphabet_available_test'() ->
    ?assertEqual(87,
		 scrabble_score:score("abcdefghijklmnopqrstuvwxyz")).
