%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/42dd0cea20498fd544b152c4e2c0a419bb7e266a/exercises/satellite/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(satellite_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_empty_tree_test_'() ->
    {"Empty tree",
     ?_assertEqual(#{},
		   satellite:tree_from_traversals([], []))}.

'2_tree_with_one_item_test_'() ->
    {"Tree with one item",
     ?_assertEqual(#{l => #{}, r => #{}, v => "a"},
		   satellite:tree_from_traversals(["a"], ["a"]))}.

'3_tree_with_many_items_test_'() ->
    {"Tree with many items",
     ?_assertEqual(#{l => #{l => #{}, r => #{}, v => "i"},
		     r =>
			 #{l => #{l => #{}, r => #{}, v => "f"},
			   r => #{l => #{}, r => #{}, v => "r"}, v => "x"},
		     v => "a"},
		   satellite:tree_from_traversals(["a", "i", "x", "f",
						   "r"],
						  ["i", "a", "f", "x", "r"]))}.

'4_reject_traversals_of_different_length_test_'() ->
    {"Reject traversals of different length",
     ?_assertError(_,
		   satellite:tree_from_traversals(["a", "b"],
						  ["b", "a", "r"]))}.

'5_reject_inconsistent_traversals_of_same_length_test_'() ->
    {"Reject inconsistent traversals of same "
     "length",
     ?_assertError(_,
		   satellite:tree_from_traversals(["x", "y", "z"],
						  ["a", "b", "c"]))}.

'6_reject_traversals_with_repeated_items_test_'() ->
    {"Reject traversals with repeated items",
     ?_assertError(_,
		   satellite:tree_from_traversals(["a", "b", "a"],
						  ["b", "a", "a"]))}.
