%% Based on canonical data version 1.0.0.1
%% Generated with 'testgen v0.1.0'
%% https://github.com/exercism/problem-specifications/raw/edf177868cfca55ede25bdd35d6780f8ecb48ffb/exercises/resistor-color/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(resistor_color_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_black_test_'() ->
    {"Black",
     ?_assertEqual(0, resistor_color:color_code(black))}.

'2_white_test_'() ->
    {"White",
     ?_assertEqual(9, resistor_color:color_code(white))}.

'3_orange_test_'() ->
    {"Orange",
     ?_assertEqual(3, resistor_color:color_code(orange))}.

'4_colors_test_'() ->
    {"Colors",
     ?_assertEqual([black, brown, red, orange, yellow, green,
		    blue, violet, grey, white],
		   resistor_color:colors())}.
