%% Based on canonical data version 1.1.0-1
%% https://github.com/exercism/problem-specifications/raw/master/exercises/hello-world/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(hello_world_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").


-define(assertStringEqual(Expect, Expr),
        begin ((fun () ->
            __X = (Expect),
            __Y = (Expr),
            case string:equal(__X, __Y) of
                true -> ok;
                false -> erlang:error({assertStringEqual,
                    [{module, ?MODULE},
                     {line, ?LINE},
                     {expression, (??Expr)},
                     {expected, unicode:characters_to_list(__X)},
                     {value, unicode:characters_to_list(__Y)}]})
            end
        end)())
    end).

-define(_assertStringEqual(Expect, Expr), ?_test(?assertStringEqual(Expect, Expr))).


'1_say_hi_test_'() ->
    {"Say Hi!",
     ?_assertStringEqual("Hello, World!",
			 hello_world:hello())}.
