%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/42dd0cea20498fd544b152c4e2c0a419bb7e266a/exercises/protein-translation/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(protein_translation_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_methionine_rna_sequence_test_'() ->
    {"Methionine RNA sequence",
     ?_assertMatch([methionine],
		   protein_translation:proteins("AUG"))}.

'2_phenylalanine_rna_sequence_1_test_'() ->
    {"Phenylalanine RNA sequence 1",
     ?_assertMatch([phenylalanine],
		   protein_translation:proteins("UUU"))}.

'3_phenylalanine_rna_sequence_2_test_'() ->
    {"Phenylalanine RNA sequence 2",
     ?_assertMatch([phenylalanine],
		   protein_translation:proteins("UUC"))}.

'4_leucine_rna_sequence_1_test_'() ->
    {"Leucine RNA sequence 1",
     ?_assertMatch([leucine],
		   protein_translation:proteins("UUA"))}.

'5_leucine_rna_sequence_2_test_'() ->
    {"Leucine RNA sequence 2",
     ?_assertMatch([leucine],
		   protein_translation:proteins("UUG"))}.

'6_serine_rna_sequence_1_test_'() ->
    {"Serine RNA sequence 1",
     ?_assertMatch([serine],
		   protein_translation:proteins("UCU"))}.

'7_serine_rna_sequence_2_test_'() ->
    {"Serine RNA sequence 2",
     ?_assertMatch([serine],
		   protein_translation:proteins("UCC"))}.

'8_serine_rna_sequence_3_test_'() ->
    {"Serine RNA sequence 3",
     ?_assertMatch([serine],
		   protein_translation:proteins("UCA"))}.

'9_serine_rna_sequence_4_test_'() ->
    {"Serine RNA sequence 4",
     ?_assertMatch([serine],
		   protein_translation:proteins("UCG"))}.

'10_tyrosine_rna_sequence_1_test_'() ->
    {"Tyrosine RNA sequence 1",
     ?_assertMatch([tyrosine],
		   protein_translation:proteins("UAU"))}.

'11_tyrosine_rna_sequence_2_test_'() ->
    {"Tyrosine RNA sequence 2",
     ?_assertMatch([tyrosine],
		   protein_translation:proteins("UAC"))}.

'12_cysteine_rna_sequence_1_test_'() ->
    {"Cysteine RNA sequence 1",
     ?_assertMatch([cysteine],
		   protein_translation:proteins("UGU"))}.

'13_cysteine_rna_sequence_2_test_'() ->
    {"Cysteine RNA sequence 2",
     ?_assertMatch([cysteine],
		   protein_translation:proteins("UGC"))}.

'14_tryptophan_rna_sequence_test_'() ->
    {"Tryptophan RNA sequence",
     ?_assertMatch([tryptophan],
		   protein_translation:proteins("UGG"))}.

'15_stop_codon_rna_sequence_1_test_'() ->
    {"STOP codon RNA sequence 1",
     ?_assertMatch([], protein_translation:proteins("UAA"))}.

'16_stop_codon_rna_sequence_2_test_'() ->
    {"STOP codon RNA sequence 2",
     ?_assertMatch([], protein_translation:proteins("UAG"))}.

'17_stop_codon_rna_sequence_3_test_'() ->
    {"STOP codon RNA sequence 3",
     ?_assertMatch([], protein_translation:proteins("UGA"))}.

'18_translate_rna_strand_into_correct_protein_list_test_'() ->
    {"Translate RNA strand into correct protein "
     "list",
     ?_assertMatch([methionine, phenylalanine, tryptophan],
		   protein_translation:proteins("AUGUUUUGG"))}.

'19_translation_stops_if_stop_codon_at_beginning_of_sequence_test_'() ->
    {"Translation stops if STOP codon at beginning "
     "of sequence",
     ?_assertMatch([],
		   protein_translation:proteins("UAGUGG"))}.

'20_translation_stops_if_stop_codon_at_end_of_two_codon_sequence_test_'() ->
    {"Translation stops if STOP codon at end "
     "of two-codon sequence",
     ?_assertMatch([tryptophan],
		   protein_translation:proteins("UGGUAG"))}.

'21_translation_stops_if_stop_codon_at_end_of_three_codon_sequence_test_'() ->
    {"Translation stops if STOP codon at end "
     "of three-codon sequence",
     ?_assertMatch([methionine, phenylalanine],
		   protein_translation:proteins("AUGUUUUAA"))}.

'22_translation_stops_if_stop_codon_in_middle_of_three_codon_sequence_test_'() ->
    {"Translation stops if STOP codon in middle "
     "of three-codon sequence",
     ?_assertMatch([tryptophan],
		   protein_translation:proteins("UGGUAGUGG"))}.

'23_translation_stops_if_stop_codon_in_middle_of_six_codon_sequence_test_'() ->
    {"Translation stops if STOP codon in middle "
     "of six-codon sequence",
     ?_assertMatch([tryptophan, cysteine, tyrosine],
		   protein_translation:proteins("UGGUGUUAUUAAUGGUUU"))}.
