%% Based on canonical data version 1.1.1
%% https://github.com/exercism/problem-specifications/raw/master/exercises/protein-translation/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(protein_translation_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_methionine_rna_sequence_test'() ->
    ?assertMatch([methionine],
		 protein_translation:proteins("AUG")).

'2_phenylalanine_rna_sequence_1_test'() ->
    ?assertMatch([phenylalanine],
		 protein_translation:proteins("UUU")).

'3_phenylalanine_rna_sequence_2_test'() ->
    ?assertMatch([phenylalanine],
		 protein_translation:proteins("UUC")).

'4_leucine_rna_sequence_1_test'() ->
    ?assertMatch([leucine],
		 protein_translation:proteins("UUA")).

'5_leucine_rna_sequence_2_test'() ->
    ?assertMatch([leucine],
		 protein_translation:proteins("UUG")).

'6_serine_rna_sequence_1_test'() ->
    ?assertMatch([serine],
		 protein_translation:proteins("UCU")).

'7_serine_rna_sequence_2_test'() ->
    ?assertMatch([serine],
		 protein_translation:proteins("UCC")).

'8_serine_rna_sequence_3_test'() ->
    ?assertMatch([serine],
		 protein_translation:proteins("UCA")).

'9_serine_rna_sequence_4_test'() ->
    ?assertMatch([serine],
		 protein_translation:proteins("UCG")).

'10_tyrosine_rna_sequence_1_test'() ->
    ?assertMatch([tyrosine],
		 protein_translation:proteins("UAU")).

'11_tyrosine_rna_sequence_2_test'() ->
    ?assertMatch([tyrosine],
		 protein_translation:proteins("UAC")).

'12_cysteine_rna_sequence_1_test'() ->
    ?assertMatch([cysteine],
		 protein_translation:proteins("UGU")).

'13_cysteine_rna_sequence_2_test'() ->
    ?assertMatch([cysteine],
		 protein_translation:proteins("UGC")).

'14_tryptophan_rna_sequence_test'() ->
    ?assertMatch([tryptophan],
		 protein_translation:proteins("UGG")).

'15_stop_codon_rna_sequence_1_test'() ->
    ?assertMatch([], protein_translation:proteins("UAA")).

'16_stop_codon_rna_sequence_2_test'() ->
    ?assertMatch([], protein_translation:proteins("UAG")).

'17_stop_codon_rna_sequence_3_test'() ->
    ?assertMatch([], protein_translation:proteins("UGA")).

'18_translate_rna_strand_into_correct_protein_list_test'() ->
    ?assertMatch([methionine, phenylalanine, tryptophan],
		 protein_translation:proteins("AUGUUUUGG")).

'19_translation_stops_if_stop_codon_at_beginning_of_sequence_test'() ->
    ?assertMatch([],
		 protein_translation:proteins("UAGUGG")).

'20_translation_stops_if_stop_codon_at_end_of_two_codon_sequence_test'() ->
    ?assertMatch([tryptophan],
		 protein_translation:proteins("UGGUAG")).

'21_translation_stops_if_stop_codon_at_end_of_three_codon_sequence_test'() ->
    ?assertMatch([methionine, phenylalanine],
		 protein_translation:proteins("AUGUUUUAA")).

'22_translation_stops_if_stop_codon_in_middle_of_three_codon_sequence_test'() ->
    ?assertMatch([tryptophan],
		 protein_translation:proteins("UGGUAGUGG")).

'23_translation_stops_if_stop_codon_in_middle_of_six_codon_sequence_test'() ->
    ?assertMatch([tryptophan, cysteine, tyrosine],
		 protein_translation:proteins("UGGUGUUAUUAAUGGUUU")).
