%% Based on canonical data version 1.2.0-1
%% https://github.com/exercism/problem-specifications/raw/master/exercises/two-fer/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(two_fer_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_no_name_given_test'() ->
    ?assertEqual("One for you, one for me.",
		 two_fer:two_fer()).

'2_a_name_given_test'() ->
    ?assertEqual("One for Alice, one for me.",
		 two_fer:two_fer("Alice")).

'3_another_name_given_test'() ->
    ?assertEqual("One for Bob, one for me.",
		 two_fer:two_fer("Bob")).
