%% Based on canonical data version 1.4.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/leap/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(leap_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_year_not_divisible_by_4_common_year_test'() ->
    ?assertNot(leap:leap_year(2015)).

'2_year_divisible_by_4_not_divisible_by_100_leap_year_test'() ->
    ?assert(leap:leap_year(1996)).

'3_year_divisible_by_100_not_divisible_by_400_common_year_test'() ->
    ?assertNot(leap:leap_year(2100)).

'4_year_divisible_by_400_leap_year_test'() ->
    ?assert(leap:leap_year(2000)).

'5_year_divisible_by_200_not_divisible_by_400_common_year_test'() ->
    ?assertNot(leap:leap_year(1800)).
