-module(leap_tests).

% This file is automatically generated from the exercises canonical data.

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").


year_not_divisible_by_4_common_year_test() ->
    ?assertNot(leap:leap_year(2015)).

year_divisible_by_4_not_divisible_by_100_leap_year_test() ->
    ?assert(leap:leap_year(2020)).

year_divisible_by_100_not_divisible_by_400_common_year_test() ->
    ?assertNot(leap:leap_year(2100)).

year_divisible_by_400_leap_year_test() ->
    ?assert(leap:leap_year(2000)).

version_test() -> ?assertMatch(3, leap:test_version()).
