%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/37f7831be7b29edf05a5f9e56825c125c4eaf707/exercises/meetup/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(meetup_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_when_teenth_monday_is_the_13th_the_first_day_of_the_teenth_week_test_'() ->
    {"when teenth Monday is the 13th, the "
     "first day of the teenth week",
     ?_assertEqual({2013, 5, 13},
		   meetup:meetup(2013, 5, monday, teenth))}.

'2_when_teenth_monday_is_the_19th_the_last_day_of_the_teenth_week_test_'() ->
    {"when teenth Monday is the 19th, the "
     "last day of the teenth week",
     ?_assertEqual({2013, 8, 19},
		   meetup:meetup(2013, 8, monday, teenth))}.

'3_when_teenth_monday_is_some_day_in_the_middle_of_the_teenth_week_test_'() ->
    {"when teenth Monday is some day in the "
     "middle of the teenth week",
     ?_assertEqual({2013, 9, 16},
		   meetup:meetup(2013, 9, monday, teenth))}.

'4_when_teenth_tuesday_is_the_19th_the_last_day_of_the_teenth_week_test_'() ->
    {"when teenth Tuesday is the 19th, the "
     "last day of the teenth week",
     ?_assertEqual({2013, 3, 19},
		   meetup:meetup(2013, 3, tuesday, teenth))}.

'5_when_teenth_tuesday_is_some_day_in_the_middle_of_the_teenth_week_test_'() ->
    {"when teenth Tuesday is some day in the "
     "middle of the teenth week",
     ?_assertEqual({2013, 4, 16},
		   meetup:meetup(2013, 4, tuesday, teenth))}.

'6_when_teenth_tuesday_is_the_13th_the_first_day_of_the_teenth_week_test_'() ->
    {"when teenth Tuesday is the 13th, the "
     "first day of the teenth week",
     ?_assertEqual({2013, 8, 13},
		   meetup:meetup(2013, 8, tuesday, teenth))}.

'7_when_teenth_wednesday_is_some_day_in_the_middle_of_the_teenth_week_test_'() ->
    {"when teenth Wednesday is some day in "
     "the middle of the teenth week",
     ?_assertEqual({2013, 1, 16},
		   meetup:meetup(2013, 1, wednesday, teenth))}.

'8_when_teenth_wednesday_is_the_13th_the_first_day_of_the_teenth_week_test_'() ->
    {"when teenth Wednesday is the 13th, the "
     "first day of the teenth week",
     ?_assertEqual({2013, 2, 13},
		   meetup:meetup(2013, 2, wednesday, teenth))}.

'9_when_teenth_wednesday_is_the_19th_the_last_day_of_the_teenth_week_test_'() ->
    {"when teenth Wednesday is the 19th, the "
     "last day of the teenth week",
     ?_assertEqual({2013, 6, 19},
		   meetup:meetup(2013, 6, wednesday, teenth))}.

'10_when_teenth_thursday_is_some_day_in_the_middle_of_the_teenth_week_test_'() ->
    {"when teenth Thursday is some day in "
     "the middle of the teenth week",
     ?_assertEqual({2013, 5, 16},
		   meetup:meetup(2013, 5, thursday, teenth))}.

'11_when_teenth_thursday_is_the_13th_the_first_day_of_the_teenth_week_test_'() ->
    {"when teenth Thursday is the 13th, the "
     "first day of the teenth week",
     ?_assertEqual({2013, 6, 13},
		   meetup:meetup(2013, 6, thursday, teenth))}.

'12_when_teenth_thursday_is_the_19th_the_last_day_of_the_teenth_week_test_'() ->
    {"when teenth Thursday is the 19th, the "
     "last day of the teenth week",
     ?_assertEqual({2013, 9, 19},
		   meetup:meetup(2013, 9, thursday, teenth))}.

'13_when_teenth_friday_is_the_19th_the_last_day_of_the_teenth_week_test_'() ->
    {"when teenth Friday is the 19th, the "
     "last day of the teenth week",
     ?_assertEqual({2013, 4, 19},
		   meetup:meetup(2013, 4, friday, teenth))}.

'14_when_teenth_friday_is_some_day_in_the_middle_of_the_teenth_week_test_'() ->
    {"when teenth Friday is some day in the "
     "middle of the teenth week",
     ?_assertEqual({2013, 8, 16},
		   meetup:meetup(2013, 8, friday, teenth))}.

'15_when_teenth_friday_is_the_13th_the_first_day_of_the_teenth_week_test_'() ->
    {"when teenth Friday is the 13th, the "
     "first day of the teenth week",
     ?_assertEqual({2013, 9, 13},
		   meetup:meetup(2013, 9, friday, teenth))}.

'16_when_teenth_saturday_is_some_day_in_the_middle_of_the_teenth_week_test_'() ->
    {"when teenth Saturday is some day in "
     "the middle of the teenth week",
     ?_assertEqual({2013, 2, 16},
		   meetup:meetup(2013, 2, saturday, teenth))}.

'17_when_teenth_saturday_is_the_13th_the_first_day_of_the_teenth_week_test_'() ->
    {"when teenth Saturday is the 13th, the "
     "first day of the teenth week",
     ?_assertEqual({2013, 4, 13},
		   meetup:meetup(2013, 4, saturday, teenth))}.

'18_when_teenth_saturday_is_the_19th_the_last_day_of_the_teenth_week_test_'() ->
    {"when teenth Saturday is the 19th, the "
     "last day of the teenth week",
     ?_assertEqual({2013, 10, 19},
		   meetup:meetup(2013, 10, saturday, teenth))}.

'19_when_teenth_sunday_is_the_19th_the_last_day_of_the_teenth_week_test_'() ->
    {"when teenth Sunday is the 19th, the "
     "last day of the teenth week",
     ?_assertEqual({2013, 5, 19},
		   meetup:meetup(2013, 5, sunday, teenth))}.

'20_when_teenth_sunday_is_some_day_in_the_middle_of_the_teenth_week_test_'() ->
    {"when teenth Sunday is some day in the "
     "middle of the teenth week",
     ?_assertEqual({2013, 6, 16},
		   meetup:meetup(2013, 6, sunday, teenth))}.

'21_when_teenth_sunday_is_the_13th_the_first_day_of_the_teenth_week_test_'() ->
    {"when teenth Sunday is the 13th, the "
     "first day of the teenth week",
     ?_assertEqual({2013, 10, 13},
		   meetup:meetup(2013, 10, sunday, teenth))}.

'22_when_first_monday_is_some_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Monday is some day in the "
     "middle of the first week",
     ?_assertEqual({2013, 3, 4},
		   meetup:meetup(2013, 3, monday, first))}.

'23_when_first_monday_is_the_1st_the_first_day_of_the_first_week_test_'() ->
    {"when first Monday is the 1st, the first "
     "day of the first week",
     ?_assertEqual({2013, 4, 1},
		   meetup:meetup(2013, 4, monday, first))}.

'24_when_first_tuesday_is_the_7th_the_last_day_of_the_first_week_test_'() ->
    {"when first Tuesday is the 7th, the last "
     "day of the first week",
     ?_assertEqual({2013, 5, 7},
		   meetup:meetup(2013, 5, tuesday, first))}.

'25_when_first_tuesday_is_some_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Tuesday is some day in the "
     "middle of the first week",
     ?_assertEqual({2013, 6, 4},
		   meetup:meetup(2013, 6, tuesday, first))}.

'26_when_first_wednesday_is_some_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Wednesday is some day in "
     "the middle of the first week",
     ?_assertEqual({2013, 7, 3},
		   meetup:meetup(2013, 7, wednesday, first))}.

'27_when_first_wednesday_is_the_7th_the_last_day_of_the_first_week_test_'() ->
    {"when first Wednesday is the 7th, the "
     "last day of the first week",
     ?_assertEqual({2013, 8, 7},
		   meetup:meetup(2013, 8, wednesday, first))}.

'28_when_first_thursday_is_some_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Thursday is some day in the "
     "middle of the first week",
     ?_assertEqual({2013, 9, 5},
		   meetup:meetup(2013, 9, thursday, first))}.

'29_when_first_thursday_is_another_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Thursday is another day in "
     "the middle of the first week",
     ?_assertEqual({2013, 10, 3},
		   meetup:meetup(2013, 10, thursday, first))}.

'30_when_first_friday_is_the_1st_the_first_day_of_the_first_week_test_'() ->
    {"when first Friday is the 1st, the first "
     "day of the first week",
     ?_assertEqual({2013, 11, 1},
		   meetup:meetup(2013, 11, friday, first))}.

'31_when_first_friday_is_some_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Friday is some day in the "
     "middle of the first week",
     ?_assertEqual({2013, 12, 6},
		   meetup:meetup(2013, 12, friday, first))}.

'32_when_first_saturday_is_some_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Saturday is some day in the "
     "middle of the first week",
     ?_assertEqual({2013, 1, 5},
		   meetup:meetup(2013, 1, saturday, first))}.

'33_when_first_saturday_is_another_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Saturday is another day in "
     "the middle of the first week",
     ?_assertEqual({2013, 2, 2},
		   meetup:meetup(2013, 2, saturday, first))}.

'34_when_first_sunday_is_some_day_in_the_middle_of_the_first_week_test_'() ->
    {"when first Sunday is some day in the "
     "middle of the first week",
     ?_assertEqual({2013, 3, 3},
		   meetup:meetup(2013, 3, sunday, first))}.

'35_when_first_sunday_is_the_7th_the_last_day_of_the_first_week_test_'() ->
    {"when first Sunday is the 7th, the last "
     "day of the first week",
     ?_assertEqual({2013, 4, 7},
		   meetup:meetup(2013, 4, sunday, first))}.

'36_when_second_monday_is_some_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Monday is some day in the "
     "middle of the second week",
     ?_assertEqual({2013, 3, 11},
		   meetup:meetup(2013, 3, monday, second))}.

'37_when_second_monday_is_the_8th_the_first_day_of_the_second_week_test_'() ->
    {"when second Monday is the 8th, the first "
     "day of the second week",
     ?_assertEqual({2013, 4, 8},
		   meetup:meetup(2013, 4, monday, second))}.

'38_when_second_tuesday_is_the_14th_the_last_day_of_the_second_week_test_'() ->
    {"when second Tuesday is the 14th, the "
     "last day of the second week",
     ?_assertEqual({2013, 5, 14},
		   meetup:meetup(2013, 5, tuesday, second))}.

'39_when_second_tuesday_is_some_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Tuesday is some day in the "
     "middle of the second week",
     ?_assertEqual({2013, 6, 11},
		   meetup:meetup(2013, 6, tuesday, second))}.

'40_when_second_wednesday_is_some_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Wednesday is some day in "
     "the middle of the second week",
     ?_assertEqual({2013, 7, 10},
		   meetup:meetup(2013, 7, wednesday, second))}.

'41_when_second_wednesday_is_the_14th_the_last_day_of_the_second_week_test_'() ->
    {"when second Wednesday is the 14th, the "
     "last day of the second week",
     ?_assertEqual({2013, 8, 14},
		   meetup:meetup(2013, 8, wednesday, second))}.

'42_when_second_thursday_is_some_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Thursday is some day in "
     "the middle of the second week",
     ?_assertEqual({2013, 9, 12},
		   meetup:meetup(2013, 9, thursday, second))}.

'43_when_second_thursday_is_another_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Thursday is another day "
     "in the middle of the second week",
     ?_assertEqual({2013, 10, 10},
		   meetup:meetup(2013, 10, thursday, second))}.

'44_when_second_friday_is_the_8th_the_first_day_of_the_second_week_test_'() ->
    {"when second Friday is the 8th, the first "
     "day of the second week",
     ?_assertEqual({2013, 11, 8},
		   meetup:meetup(2013, 11, friday, second))}.

'45_when_second_friday_is_some_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Friday is some day in the "
     "middle of the second week",
     ?_assertEqual({2013, 12, 13},
		   meetup:meetup(2013, 12, friday, second))}.

'46_when_second_saturday_is_some_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Saturday is some day in "
     "the middle of the second week",
     ?_assertEqual({2013, 1, 12},
		   meetup:meetup(2013, 1, saturday, second))}.

'47_when_second_saturday_is_another_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Saturday is another day "
     "in the middle of the second week",
     ?_assertEqual({2013, 2, 9},
		   meetup:meetup(2013, 2, saturday, second))}.

'48_when_second_sunday_is_some_day_in_the_middle_of_the_second_week_test_'() ->
    {"when second Sunday is some day in the "
     "middle of the second week",
     ?_assertEqual({2013, 3, 10},
		   meetup:meetup(2013, 3, sunday, second))}.

'49_when_second_sunday_is_the_14th_the_last_day_of_the_second_week_test_'() ->
    {"when second Sunday is the 14th, the "
     "last day of the second week",
     ?_assertEqual({2013, 4, 14},
		   meetup:meetup(2013, 4, sunday, second))}.

'50_when_third_monday_is_some_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Monday is some day in the "
     "middle of the third week",
     ?_assertEqual({2013, 3, 18},
		   meetup:meetup(2013, 3, monday, third))}.

'51_when_third_monday_is_the_15th_the_first_day_of_the_third_week_test_'() ->
    {"when third Monday is the 15th, the first "
     "day of the third week",
     ?_assertEqual({2013, 4, 15},
		   meetup:meetup(2013, 4, monday, third))}.

'52_when_third_tuesday_is_the_21st_the_last_day_of_the_third_week_test_'() ->
    {"when third Tuesday is the 21st, the "
     "last day of the third week",
     ?_assertEqual({2013, 5, 21},
		   meetup:meetup(2013, 5, tuesday, third))}.

'53_when_third_tuesday_is_some_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Tuesday is some day in the "
     "middle of the third week",
     ?_assertEqual({2013, 6, 18},
		   meetup:meetup(2013, 6, tuesday, third))}.

'54_when_third_wednesday_is_some_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Wednesday is some day in "
     "the middle of the third week",
     ?_assertEqual({2013, 7, 17},
		   meetup:meetup(2013, 7, wednesday, third))}.

'55_when_third_wednesday_is_the_21st_the_last_day_of_the_third_week_test_'() ->
    {"when third Wednesday is the 21st, the "
     "last day of the third week",
     ?_assertEqual({2013, 8, 21},
		   meetup:meetup(2013, 8, wednesday, third))}.

'56_when_third_thursday_is_some_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Thursday is some day in the "
     "middle of the third week",
     ?_assertEqual({2013, 9, 19},
		   meetup:meetup(2013, 9, thursday, third))}.

'57_when_third_thursday_is_another_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Thursday is another day in "
     "the middle of the third week",
     ?_assertEqual({2013, 10, 17},
		   meetup:meetup(2013, 10, thursday, third))}.

'58_when_third_friday_is_the_15th_the_first_day_of_the_third_week_test_'() ->
    {"when third Friday is the 15th, the first "
     "day of the third week",
     ?_assertEqual({2013, 11, 15},
		   meetup:meetup(2013, 11, friday, third))}.

'59_when_third_friday_is_some_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Friday is some day in the "
     "middle of the third week",
     ?_assertEqual({2013, 12, 20},
		   meetup:meetup(2013, 12, friday, third))}.

'60_when_third_saturday_is_some_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Saturday is some day in the "
     "middle of the third week",
     ?_assertEqual({2013, 1, 19},
		   meetup:meetup(2013, 1, saturday, third))}.

'61_when_third_saturday_is_another_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Saturday is another day in "
     "the middle of the third week",
     ?_assertEqual({2013, 2, 16},
		   meetup:meetup(2013, 2, saturday, third))}.

'62_when_third_sunday_is_some_day_in_the_middle_of_the_third_week_test_'() ->
    {"when third Sunday is some day in the "
     "middle of the third week",
     ?_assertEqual({2013, 3, 17},
		   meetup:meetup(2013, 3, sunday, third))}.

'63_when_third_sunday_is_the_21st_the_last_day_of_the_third_week_test_'() ->
    {"when third Sunday is the 21st, the last "
     "day of the third week",
     ?_assertEqual({2013, 4, 21},
		   meetup:meetup(2013, 4, sunday, third))}.

'64_when_fourth_monday_is_some_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Monday is some day in the "
     "middle of the fourth week",
     ?_assertEqual({2013, 3, 25},
		   meetup:meetup(2013, 3, monday, fourth))}.

'65_when_fourth_monday_is_the_22nd_the_first_day_of_the_fourth_week_test_'() ->
    {"when fourth Monday is the 22nd, the "
     "first day of the fourth week",
     ?_assertEqual({2013, 4, 22},
		   meetup:meetup(2013, 4, monday, fourth))}.

'66_when_fourth_tuesday_is_the_28th_the_last_day_of_the_fourth_week_test_'() ->
    {"when fourth Tuesday is the 28th, the "
     "last day of the fourth week",
     ?_assertEqual({2013, 5, 28},
		   meetup:meetup(2013, 5, tuesday, fourth))}.

'67_when_fourth_tuesday_is_some_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Tuesday is some day in the "
     "middle of the fourth week",
     ?_assertEqual({2013, 6, 25},
		   meetup:meetup(2013, 6, tuesday, fourth))}.

'68_when_fourth_wednesday_is_some_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Wednesday is some day in "
     "the middle of the fourth week",
     ?_assertEqual({2013, 7, 24},
		   meetup:meetup(2013, 7, wednesday, fourth))}.

'69_when_fourth_wednesday_is_the_28th_the_last_day_of_the_fourth_week_test_'() ->
    {"when fourth Wednesday is the 28th, the "
     "last day of the fourth week",
     ?_assertEqual({2013, 8, 28},
		   meetup:meetup(2013, 8, wednesday, fourth))}.

'70_when_fourth_thursday_is_some_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Thursday is some day in "
     "the middle of the fourth week",
     ?_assertEqual({2013, 9, 26},
		   meetup:meetup(2013, 9, thursday, fourth))}.

'71_when_fourth_thursday_is_another_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Thursday is another day "
     "in the middle of the fourth week",
     ?_assertEqual({2013, 10, 24},
		   meetup:meetup(2013, 10, thursday, fourth))}.

'72_when_fourth_friday_is_the_22nd_the_first_day_of_the_fourth_week_test_'() ->
    {"when fourth Friday is the 22nd, the "
     "first day of the fourth week",
     ?_assertEqual({2013, 11, 22},
		   meetup:meetup(2013, 11, friday, fourth))}.

'73_when_fourth_friday_is_some_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Friday is some day in the "
     "middle of the fourth week",
     ?_assertEqual({2013, 12, 27},
		   meetup:meetup(2013, 12, friday, fourth))}.

'74_when_fourth_saturday_is_some_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Saturday is some day in "
     "the middle of the fourth week",
     ?_assertEqual({2013, 1, 26},
		   meetup:meetup(2013, 1, saturday, fourth))}.

'75_when_fourth_saturday_is_another_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Saturday is another day "
     "in the middle of the fourth week",
     ?_assertEqual({2013, 2, 23},
		   meetup:meetup(2013, 2, saturday, fourth))}.

'76_when_fourth_sunday_is_some_day_in_the_middle_of_the_fourth_week_test_'() ->
    {"when fourth Sunday is some day in the "
     "middle of the fourth week",
     ?_assertEqual({2013, 3, 24},
		   meetup:meetup(2013, 3, sunday, fourth))}.

'77_when_fourth_sunday_is_the_28th_the_last_day_of_the_fourth_week_test_'() ->
    {"when fourth Sunday is the 28th, the "
     "last day of the fourth week",
     ?_assertEqual({2013, 4, 28},
		   meetup:meetup(2013, 4, sunday, fourth))}.

'78_last_monday_in_a_month_with_four_mondays_test_'() ->
    {"last Monday in a month with four Mondays",
     ?_assertEqual({2013, 3, 25},
		   meetup:meetup(2013, 3, monday, last))}.

'79_last_monday_in_a_month_with_five_mondays_test_'() ->
    {"last Monday in a month with five Mondays",
     ?_assertEqual({2013, 4, 29},
		   meetup:meetup(2013, 4, monday, last))}.

'80_last_tuesday_in_a_month_with_four_tuesdays_test_'() ->
    {"last Tuesday in a month with four Tuesdays",
     ?_assertEqual({2013, 5, 28},
		   meetup:meetup(2013, 5, tuesday, last))}.

'81_last_tuesday_in_another_month_with_four_tuesdays_test_'() ->
    {"last Tuesday in another month with four "
     "Tuesdays",
     ?_assertEqual({2013, 6, 25},
		   meetup:meetup(2013, 6, tuesday, last))}.

'82_last_wednesday_in_a_month_with_five_wednesdays_test_'() ->
    {"last Wednesday in a month with five "
     "Wednesdays",
     ?_assertEqual({2013, 7, 31},
		   meetup:meetup(2013, 7, wednesday, last))}.

'83_last_wednesday_in_a_month_with_four_wednesdays_test_'() ->
    {"last Wednesday in a month with four "
     "Wednesdays",
     ?_assertEqual({2013, 8, 28},
		   meetup:meetup(2013, 8, wednesday, last))}.

'84_last_thursday_in_a_month_with_four_thursdays_test_'() ->
    {"last Thursday in a month with four Thursdays",
     ?_assertEqual({2013, 9, 26},
		   meetup:meetup(2013, 9, thursday, last))}.

'85_last_thursday_in_a_month_with_five_thursdays_test_'() ->
    {"last Thursday in a month with five Thursdays",
     ?_assertEqual({2013, 10, 31},
		   meetup:meetup(2013, 10, thursday, last))}.

'86_last_friday_in_a_month_with_five_fridays_test_'() ->
    {"last Friday in a month with five Fridays",
     ?_assertEqual({2013, 11, 29},
		   meetup:meetup(2013, 11, friday, last))}.

'87_last_friday_in_a_month_with_four_fridays_test_'() ->
    {"last Friday in a month with four Fridays",
     ?_assertEqual({2013, 12, 27},
		   meetup:meetup(2013, 12, friday, last))}.

'88_last_saturday_in_a_month_with_four_saturdays_test_'() ->
    {"last Saturday in a month with four Saturdays",
     ?_assertEqual({2013, 1, 26},
		   meetup:meetup(2013, 1, saturday, last))}.

'89_last_saturday_in_another_month_with_four_saturdays_test_'() ->
    {"last Saturday in another month with "
     "four Saturdays",
     ?_assertEqual({2013, 2, 23},
		   meetup:meetup(2013, 2, saturday, last))}.

'90_last_sunday_in_a_month_with_five_sundays_test_'() ->
    {"last Sunday in a month with five Sundays",
     ?_assertEqual({2013, 3, 31},
		   meetup:meetup(2013, 3, sunday, last))}.

'91_last_sunday_in_a_month_with_four_sundays_test_'() ->
    {"last Sunday in a month with four Sundays",
     ?_assertEqual({2013, 4, 28},
		   meetup:meetup(2013, 4, sunday, last))}.

'92_when_last_wednesday_in_february_in_a_leap_year_is_the_29th_test_'() ->
    {"when last Wednesday in February in a "
     "leap year is the 29th",
     ?_assertEqual({2012, 2, 29},
		   meetup:meetup(2012, 2, wednesday, last))}.

'93_last_wednesday_in_december_that_is_also_the_last_day_of_the_year_test_'() ->
    {"last Wednesday in December that is also "
     "the last day of the year",
     ?_assertEqual({2014, 12, 31},
		   meetup:meetup(2014, 12, wednesday, last))}.

'94_when_last_sunday_in_february_in_a_non_leap_year_is_not_the_29th_test_'() ->
    {"when last Sunday in February in a non-leap "
     "year is not the 29th",
     ?_assertEqual({2015, 2, 22},
		   meetup:meetup(2015, 2, sunday, last))}.

'95_when_first_friday_is_the_7th_the_last_day_of_the_first_week_test_'() ->
    {"when first Friday is the 7th, the last "
     "day of the first week",
     ?_assertEqual({2012, 12, 7},
		   meetup:meetup(2012, 12, friday, first))}.
