%% Based on canonical data version 2.2.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/queen-attack/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(queen_attack_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_can_not_attack_test'() ->
    ?assertNot(queen_attack:can_attack({4, 2}, {6, 6})).

'2_can_attack_on_same_row_test'() ->
    ?assert(queen_attack:can_attack({4, 2}, {6, 2})).

'3_can_attack_on_same_column_test'() ->
    ?assert(queen_attack:can_attack({5, 4}, {5, 2})).

'4_can_attack_on_first_diagonal_test'() ->
    ?assert(queen_attack:can_attack({2, 2}, {4, 0})).

'5_can_attack_on_second_diagonal_test'() ->
    ?assert(queen_attack:can_attack({2, 2}, {1, 3})).

'6_can_attack_on_third_diagonal_test'() ->
    ?assert(queen_attack:can_attack({2, 2}, {1, 1})).

'7_can_attack_on_fourth_diagonal_test'() ->
    ?assert(queen_attack:can_attack({2, 2}, {5, 5})).
