%% Generated with 'testgen v0.2.0'
%% Revision 1 of the exercises generator was used
%% https://github.com/exercism/problem-specifications/raw/42dd0cea20498fd544b152c4e2c0a419bb7e266a/exercises/transpose/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(transpose_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_empty_string_test_'() ->
    Input=[

    ],
    Expected=[

    ],
    {"empty string",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'2_two_characters_in_a_row_test_'() ->
    Input=[
        "A1"
    ],
    Expected=[
        "A",
        "1"
    ],
    {"two characters in a row",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'3_two_characters_in_a_column_test_'() ->
    Input=[
        "A",
        "1"
    ],
    Expected=[
        "A1"
    ],
    {"two characters in a column",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'4_simple_test_'() ->
    Input=[
        "ABC",
        "123"
    ],
    Expected=[
        "A1",
        "B2",
        "C3"
    ],
    {"simple",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'5_single_line_test_'() ->
    Input=[
        "Single line."
    ],
    Expected=[
        "S",
        "i",
        "n",
        "g",
        "l",
        "e",
        " ",
        "l",
        "i",
        "n",
        "e",
        "."
    ],
    {"single line",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'6_first_line_longer_than_second_line_test_'() ->
    Input=[
        "The fourth line.",
        "The fifth line."
    ],
    Expected=[
        "TT",
        "hh",
        "ee",
        "  ",
        "ff",
        "oi",
        "uf",
        "rt",
        "th",
        "h ",
        " l",
        "li",
        "in",
        "ne",
        "e.",
        "."
    ],
    {"first line longer than second line",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'7_second_line_longer_than_first_line_test_'() ->
    Input=[
        "The first line.",
        "The second line."
    ],
    Expected=[
        "TT",
        "hh",
        "ee",
        "  ",
        "fs",
        "ie",
        "rc",
        "so",
        "tn",
        " d",
        "l ",
        "il",
        "ni",
        "en",
        ".e",
        " ."
    ],
    {"second line longer than first line",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'8_mixed_line_length_test_'() ->
    Input=[
        "The longest line.",
        "A long line.",
        "A longer line.",
        "A line."
    ],
    Expected=[
        "TAAA",
        "h   ",
        "elll",
        " ooi",
        "lnnn",
        "ogge",
        "n e.",
        "glr",
        "ei ",
        "snl",
        "tei",
        " .n",
        "l e",
        "i .",
        "n",
        "e",
        "."
    ],
    {"mixed line length",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'9_square_test_'() ->
    Input=[
        "HEART",
        "EMBER",
        "ABUSE",
        "RESIN",
        "TREND"
    ],
    Expected=[
        "HEART",
        "EMBER",
        "ABUSE",
        "RESIN",
        "TREND"
    ],
    {"square",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'10_rectangle_test_'() ->
    Input=[
        "FRACTURE",
        "OUTLINED",
        "BLOOMING",
        "SEPTETTE"
    ],
    Expected=[
        "FOBS",
        "RULE",
        "ATOP",
        "CLOT",
        "TIME",
        "UNIT",
        "RENT",
        "EDGE"
    ],
    {"rectangle",
     ?_assertEqual(Expected, transpose:transpose(Input))}.

'11_triangle_test_'() ->
    Input=[
        "T",
        "EE",
        "AAA",
        "SSSS",
        "EEEEE",
        "RRRRRR"
    ],
    Expected=[
        "TEASER",
        " EASER",
        "  ASER",
        "   SER",
        "    ER",
        "     R"
    ],
    {"triangle",
     ?_assertEqual(Expected, transpose:transpose(Input))}.
