%% Based on canonical data version 1.1.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/diamond/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(diamond_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_degenerate_case_with_a_single_a_row_test'() ->
    Expected=[
        "A"
    ],
    ?assertEqual(Expected, diamond:rows("A")).

'2_degenerate_case_with_no_row_containing_3_distinct_groups_of_spaces_test'() ->
    Expected=[
        " A ",
        "B B",
        " A "
    ],
    ?assertEqual(Expected, diamond:rows("B")).

'3_smallest_non_degenerate_case_with_odd_diamond_side_length_test'() ->
    Expected=[
        "  A  ",
        " B B ",
        "C   C",
        " B B ",
        "  A  "
    ],
    ?assertEqual(Expected, diamond:rows("C")).

'4_smallest_non_degenerate_case_with_even_diamond_side_length_test'() ->
    Expected=[
        "   A   ",
        "  B B  ",
        " C   C ",
        "D     D",
        " C   C ",
        "  B B  ",
        "   A   "
    ],
    ?assertEqual(Expected, diamond:rows("D")).

'5_largest_possible_diamond_test'() ->
    Expected=[
        "                         A                         ",
        "                        B B                        ",
        "                       C   C                       ",
        "                      D     D                      ",
        "                     E       E                     ",
        "                    F         F                    ",
        "                   G           G                   ",
        "                  H             H                  ",
        "                 I               I                 ",
        "                J                 J                ",
        "               K                   K               ",
        "              L                     L              ",
        "             M                       M             ",
        "            N                         N            ",
        "           O                           O           ",
        "          P                             P          ",
        "         Q                               Q         ",
        "        R                                 R        ",
        "       S                                   S       ",
        "      T                                     T      ",
        "     U                                       U     ",
        "    V                                         V    ",
        "   W                                           W   ",
        "  X                                             X  ",
        " Y                                               Y ",
        "Z                                                 Z",
        " Y                                               Y ",
        "  X                                             X  ",
        "   W                                           W   ",
        "    V                                         V    ",
        "     U                                       U     ",
        "      T                                     T      ",
        "       S                                   S       ",
        "        R                                 R        ",
        "         Q                               Q         ",
        "          P                             P          ",
        "           O                           O           ",
        "            N                         N            ",
        "             M                       M             ",
        "              L                     L              ",
        "               K                   K               ",
        "                J                 J                ",
        "                 I               I                 ",
        "                  H             H                  ",
        "                   G           G                   ",
        "                    F         F                    ",
        "                     E       E                     ",
        "                      D     D                      ",
        "                       C   C                       ",
        "                        B B                        ",
        "                         A                         "
    ],
    ?assertEqual(Expected, diamond:rows("Z")).
