%% Based on canonical data version 2.2.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/hamming/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(hamming_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").


empty_strands_test() ->
    ?assertMatch(0, hamming:distance([], [])).

single_letter_identical_strands_test() ->
    ?assertMatch(0, hamming:distance("A", "A")).

single_letter_different_strands_test() ->
    ?assertMatch(1, hamming:distance("G", "T")).

long_identical_strands_test() ->
    ?assertMatch(0,
		 hamming:distance("GGACTGAAATCTG", "GGACTGAAATCTG")).

long_different_strands_test() ->
    ?assertMatch(9,
		 hamming:distance("GGACGGATTCTG", "AGGACGGATTCT")).

disallow_first_strand_longer_test() ->
    ?assertMatch({error,
		  "left and right strands must be of equal "
		  "length"},
		 hamming:distance("AATG", "AAA")).

disallow_second_strand_longer_test() ->
    ?assertMatch({error,
		  "left and right strands must be of equal "
		  "length"},
		 hamming:distance("ATA", "AGTG")).
