%% Based on canonical data version 1.2.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/grains/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(grains_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_square_1_test'() ->
    ?assertMatch(1, grains:square(1)).

'2_square_2_test'() ->
    ?assertMatch(2, grains:square(2)).

'3_square_3_test'() ->
    ?assertMatch(4, grains:square(3)).

'4_square_4_test'() ->
    ?assertMatch(8, grains:square(4)).

'5_square_16_test'() ->
    ?assertMatch(32768, grains:square(16)).

'6_square_32_test'() ->
    ?assertMatch(2147483648, grains:square(32)).

'7_square_64_test'() ->
    ?assertMatch(9223372036854775808, grains:square(64)).

'8_square_0_raises_an_exception_test'() ->
    ?assertMatch({error, "square must be between 1 and 64"},
		 grains:square(0)).

'9_negative_square_raises_an_exception_test'() ->
    ?assertMatch({error, "square must be between 1 and 64"},
		 grains:square(-1)).

'10_square_greater_than_64_raises_an_exception_test'() ->
    ?assertMatch({error, "square must be between 1 and 64"},
		 grains:square(65)).

'11_returns_the_total_number_of_grains_on_the_board_test'() ->
    ?assertMatch(18446744073709551615, grains:total()).
